language: scala

scala:
  - 2.13.1

jdk:
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_install:
  - cp .env.dist .env
  - docker-compose up -d
  - sbt "shared/createDbTables"

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt prep # See `build.sbt` to check out which tasks this alias performs (compile, compile test, style check...)
  - sbt test
